### ISSUE TITLE
Add "Do not show again" option to "Kubectl not found. Many features of the Kubernetes extension will not work." notification

### ISSUE THREAD

**Issue by FieteO** [vscode-kubernetes-tools/vscode-kubernetes-tools#1023]
I am using the Kubernetes extension on a system that does not have kubectl installed. I am not using it for that functionality, but rather for the helm capabilities of the extension.

Each time I open a yaml file, I get two notifications about missing kubectl:
![image](https://user-images.githubusercontent.com/41323592/148186625-30199aad-bfc9-4337-a02f-d154926801f6.png)

The menu of the notification (gear icon) only has a `Manage extension` button. It would be great if there was a `Do not show again` button so that I can disable them.

**Comment by itowlson** [comment]
I did a pass a while back to try to make the notifications less annoying, but didn't tackle the case where `kubectl` wasn't installed and the user didn't want to/couldn't install it.  As you rightly note, you should be able to work on Helm files without needing kubectl.  I'll take a look.

**Comment by itowlson** [comment]
Okay, #1030 provides for a manual config setting.  The 'not found' warning is already pretty busy and I don't want to add another button to it, especially one that, if the user hit it by mistake, would leave them in a state where nothing works and they're no longer being told why.  So it'll be a bit less convenient for your case I'm afraid, but I feel more comfortable with it for the general user base.  See the `README.md` change in that PR for details of the setting.

**Comment by FieteO** [comment]
Thanks @itowlson, that is fine as well :-)

**Comment by mcavallo-git** [comment]
> Okay, #1030 provides for a manual config setting. The 'not found' warning is already pretty busy and I don't want to add another button to it, especially one that, if the user hit it by mistake, would leave them in a state where nothing works and they're no longer being told why. So it'll be a bit less convenient for your case I'm afraid, but I feel more comfortable with it for the general user base. See the `README.md` change in that PR for details of the setting.

@itowlson 

How long do you estimate it'll be until this extension setting (suppress kubectl not found alerts) reaches a release for the VS Code extension?

I could be wrong, but I believe that the current [latest release (1.3.6)](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/releases/tag/1.3.6) doesn't include these changes, as it dropped on [12-Jan-2022](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/releases/tag/1.3.6), while the merge to resolve this issue (which contained your code for this extension setting) was completed on [17-Jan-2022](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1030).

I ask because I've tried applying the extension setting found in the [extension's `package.json` file](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/package.json) onto my local `settings.json` file as follows:
```json
{
  "vs-kubernetes": {
    "vs-kubernetes.suppress-kubectl-not-found-alerts": true
  }
}
```
But this doesn't seem to suppress the either of the `Kubectl not found. ...` or the `Kubectl command failed: ...` alerts from continuing to pop up whenever I open a helm chart in VS Code.

![kubectl-not-found__vscode-kubernetes-tools__1 3 6](https://user-images.githubusercontent.com/39514686/157766873-677051e4-1c35-45f9-bf9c-e5d1160ec993.png)

My use case is similar to the one in your quoted comment (above) in that I wish to [ use the extension for its robust syntax highlighting of helm chart YAML files ] and not [ to perform actions directly through the helm or kubectl binaries ].

Thank you very much for your continued efforts - The syntax highlighting is on-point from my experience using it over the last 4-6 months, and the fact that you not only considered adding alert suppression but took the time to write the code for it is admirable! I'm just "making sure it gets used" I suppose, hahah.

**Comment by itowlson** [comment]
@mcavallo-git you're right, that's not released yet.  We've got a couple of other things merged but not yet included in a release, so let me get one under way now, and with favourable winds it should go out early next week.

**Comment by itowlson** [comment]
I tried to release this today, but it looks like our publisher token has expired, and we only have one person right now who can create new tokens (yes, it's a problem), and it's still the weekend for him.  Crossing fingers for tomorrow.
