### ISSUE TITLE
Turn off Helm "refresh values cache" output

### ISSUE THREAD

**Issue by sc250024** [vscode-kubernetes-tools/vscode-kubernetes-tools#1026]
Greetings,

I'm using the Kubernetes tools extension, and every time I save a `values.yaml` file, the following prompt always comes up:

<img width="1247" alt="helm-values-refresh" src="https://user-images.githubusercontent.com/8792243/148745578-cedef020-60d0-4b32-8512-c2b00d0cd905.png">

It's a bit annoying, and I don't need to know every time this happens.

Is this a simple entry in the `settings.json` file?

Thank you!

**Comment by vovatikal** [comment]
very annoying

**Comment by itowlson** [comment]
Is this a recent thing?  We added a live refresh feature in the last release, so if this is new then it's probably an issue with that.  It might be debugging/logging code that's no longer needed - if we can confirm it's new then I'll check in with the author of that feature.

**Comment by itowlson** [comment]
Also, which Output channel is that on?  (That is, which selection in the drop-down shown below.) If you switch to a different channel, does it force the Output tab back to the one with the refresh message?
  
![image](https://user-images.githubusercontent.com/865538/148830094-365dd83f-3e1a-4c45-b0b3-8d850af812b5.png)

**Comment by sc250024** [comment]
I don't have the screenshot of the selection part, but it was populated with `Helm`, not `Tasks`.

**Comment by sc250024** [comment]
It seemed to stop now. Was there an update pushed?

**Comment by itowlson** [comment]
No, the last update was before the weekend.  Very odd.  Thanks for flagging this - I'll take a look.

**Comment by threaz** [comment]
Same happens to me currently. It was okay yesterday though.

VSCODE:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3

**Comment by itowlson** [comment]
@flowftw Yeah, the assumption there is that the logger is used for things that the user should know about, so it is brought front - but I bet we use it for a bunch of stuff that doesn't merit that.

I suggest one of two approaches:

1. Modify the refresh code to no longer log.
2. Modify the logger to take a parameter indicating whether the message should be force-shown (i.e. Output open and channel brought to top).  [Or to have two methods such as `log` and `logBackground`.  Or whatever!]

My suggestion for this issue is option 1, to take the logging out of the refresh code because the message is probably not needed anyway.  However I'd be happy if you want to keep the message and do option 2 so that users only see the message if they go look - whatever you feel is best.

Thanks for responding and for looking into this!

**Comment by sc250024** [comment]
Thanks guys!
