### ISSUE TITLE
Extension asks to search for CRD-based suggestions but ignores "Don't ask again" answer.

### ISSUE THREAD

**Issue by benko** [vscode-kubernetes-tools/vscode-kubernetes-tools#1053]
I believe the title says it all.
I've been looking for a setting to change this behaviour, alas.
It's really really annoying to have to watch "Error from server" every time one opens a workspace or adds a folder and there's nothing one can do about it.

**Comment by itowlson** [comment]
Can you check your config file for a setting called `ignoreRecommendations`?  "Don't ask again" is meant to set it, but I think we might have an issue where it's going in the wrong place.

**Comment by itowlson** [comment]
It looks like there are at least two issues here:

1. We try to save the preference to the _workspace_ settings file.  So users get asked again for every workspace.
2. If there's no workspace open, we silently fail to save the preference.

(Issue 2 1/2 is that the setting is called `extensions.ignoreRecommendations`, which seems to be the setting for turning off _all_ extension recommendations, including the VS Code built-in ones, or the ones recommended by a workspace.  I guess this explains why we were unwilling to set this globally, but as a user I didn't realise I was signing up to ignore _all_ future recommendations.  On the other hand, if the user has turned off recommendation using the global setting, we should respect that... so...)

The upshot for now is that if you turn off extension recommendations globally, by adding `"extensions.ignoreRecommendations": true` to your `settings.json`, then we shouldn't bother you with this again.  I'm thinking though that we should offer a k8s-specific switch-off, and that our switch-off should by default go in at global level rather than workspace level.  @lstocchi what do you reckon?

**Comment by lstocchi** [comment]
Sorry for the late response @itowlson . I definitely agree with you. We can also rely on the default `ignoreRecommendations` as a parent switch so if that one is false we don't check our custom setting but we should have one to only disable k8s-recommentations.

**Comment by lstocchi** [comment]
My proposal -> @itowlson
