### ISSUE TITLE
Logs should 'Follow Logs' and 'Run' by default

### ISSUE THREAD

**Issue by juozasg** [vscode-kubernetes-tools/vscode-kubernetes-tools#1058]
For logs display, a small change would significantly improve UX to be able to click Logs on a pod and see the logs immediately, without having first to click 'Follow Logs' and then 'Run'. And it should scroll to the bottom:

![image](https://user-images.githubusercontent.com/4100/163392429-3febb9a1-a51d-4fdc-b395-75d1aac2d591.png)

**Comment by kingdonb** [comment]
It looks like there has actually been progress on this issue upstream at:

* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1062

**Comment by kingdonb** [comment]
I had a try at https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1066 and found it makes this setting possible, you can change "Follow Logs" to be the default, and autorun has been added as an option that you can enable. We may have to call this out in our docs in order to make it more fully accessible, I'm not sure if they'll make it default behavior or if there are any drawbacks, but it worked for me!

Another open question is whether we could enable it by default, when we install the Kubernetes extension as a dependency? IDK 🤷

**Comment by lstocchi** [comment]
Closing as #1066 has been merged long ago.
