### ISSUE TITLE
Major slowness in vscode while running this extension

### ISSUE THREAD

**Issue by expruc** [vscode-kubernetes-tools/vscode-kubernetes-tools#1073]
Hello
Recently I have started experiencing problems working in vscode while this extension is running. It makes vscode stuck and I am unable to work properly. The current solution is to disable the extension.
I have noticed a high activation time of this extension, as it was more than 300 ms (the highest of all my other extensions).
This isn't related to the files parsed by this extension, as my vscode gets stuck without any opened files with this extension enabled. 

## Platform 
* OS-release: Ubuntu 20.04 Focal Fossa
* VSC version: 1.67.1
* Kubernetes extension version: 1.3.8

Thank you for the help!

**Comment by expruc** [comment]
Hi, @lstocchi and thank you for your response
After adding this setting and enabling this extension it seems to be improved a bit but still very laggy (can't save files, takes long time for vsc to shut down, etc.).  
I also tried to downgrade this extension to 1.3.7 which seems to solve the issue for now.

**Comment by lstocchi** [comment]
Thanks for the response @expruc .

Any idea what could cause it? @itowlson By looking at the last commits the only plausible explanation is crd fetching but this was also there in 1.3.7... ?? :thinking:

**Comment by itowlson** [comment]
Help > Open Process Explorer might give some insight if something is consuming a lot of CPU or memory, though it won't localise it if the slowdown is in the extension itself rather than a process.

The schema code does do some stuff in the background, but I can't see how the changes made to that for the CRD option would affect that.

I notice #1069 mentions a slowness issue - perhaps worth trying that to see if it helps?  Unfortunately we don't do canary builds from PRs so you would have to run from source.

You could try canary builds from between 1.3.7 and 1.3.8 - you can find these under https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/actions/workflows/build-dev.yml?query=event%3Apush - click a build and scroll down to the `Assets` section, then unzip the VSIX and install using the `Extensions: Install from VSIX...` command.  You may need to explicitly uninstall the marketplace version of the extension, and will need to do an uninstall-restart-reinstall cycle each time you try a build.  I realise this is a hassle but it would really help to nail down where the problem started.  Thanks!

**Comment by lstocchi** [comment]
Closing it as it's old and we pushed new releases in the meantime. We are going to release a new version in the next days, so please open a new issue if you still face a slowness with the newest version. Thanks!!
