### ISSUE TITLE
Support `~` symbol for `${HOME}` in `vs-kubernetes.kubeconfig`

### ISSUE THREAD

**Issue by felipecrs** [vscode-kubernetes-tools/vscode-kubernetes-tools#1141]
Which would be very helpful for devcontainer scenarios, like:

```jsonc
// devcontainer.json
{
  "settings": {
    "vs-kubernetes": {
      "vs-kubernetes.kubeconfig": "~/.kube/config"
    }
  }
}
```

**Comment by Tatsinnit** [comment]
💡❤️🙏 Thank you so much for this. Since this change exist in `settings.json` I think more permanent solution could be if VsCode Support variables when resolving values in settings from `settings.json`. (More context below) 

* It will be good if we could achieve the [`predefined variable`](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) enablement via `VsCode` which will lead to the auto resolution of the these variable before extension can see it. I found an old open WI around this for vscode https://github.com/microsoft/vscode/issues/2809 , please correct me in case I misunderstood anything. Thank you so much in advance.

For more thoughts, ideas share, fyi to @lstocchi , @squillace and @itowlson ☕️❤️ thanks heaps.

**Comment by felipecrs** [comment]
I agree. Perhaps this could help for now: https://www.npmjs.com/package/vscode-variables

**Comment by lstocchi** [comment]
Closing as https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1180 was merged. 
Now you can write the path as `"vs-kubernetes.kubeconfig": "${userHome}/.kube/config"`
