### ISSUE TITLE
Accessibility issue: in kubernetes cluster tree explorer

### ISSUE THREAD

**Issue by clementb49** [vscode-kubernetes-tools/vscode-kubernetes-tools#1158]
When using a screen reader like NVDA. The content of some node are not correct in kubernetes tree explorer. For example if you highlight a node in the Deployment level, the label of the node you are highlighting is the name of the namespace. The expected behaviour should be the label of the deployment node.

**Comment by Tatsinnit** [comment]
Hiya, and thank you so much @clementb49 and thank you @itowlson sounds good. Aha, I see. I ran this through NVDA - the tool announces correct info, but I see what is shows as label --> `Namespace: default`. Next is I will run this through and find out why this is behaving this way. Will loop back with solution or findings. thank you so much.  ☕️🙏❤️

**Screenshot**

![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/6233295/226210981-807b160c-1d4b-454d-94f6-2485881f00cb.png)

**Comment by Tatsinnit** [comment]
Cool, seems like this was intentional but with minor addition we can make this more informative like this:

Currently it is coming from here: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/src/components/clusterexplorer/node.resource.ts#L50 

**Proposed fix from local below** I could add label and with Namespace both informaiton like shown below.

What do you guys think, thank you so much, please do suggest any rephrase of title etc. cc: @itowlson , @lstocchi, @squillace ⛩️ 

fyi: @clementb49 

![image](https://user-images.githubusercontent.com/6233295/226213115-66ea3334-41ee-4ec9-89c5-33e32770286d.png)

**Comment by lstocchi** [comment]
Closing it as #1160 has been merged
