### ISSUE TITLE
Unable to use terminal.

### ISSUE THREAD

**Issue by lorrydriveloper** [vscode-kubernetes-tools/vscode-kubernetes-tools#1169]
I'm having an issue with the Terminal when I open it, which makes it unusable I would like to know if someone else has had the same issue and if there is a way to solve it, I tried to research, but I wasn't able to find anything. Thanks.

https://user-images.githubusercontent.com/24831929/233295330-8077e8e9-2e0c-4a35-afc7-24b0ff6c1dac.mov

**Comment by brunobernardnh** [comment]
I am also having the same issue. It works the first time but the second time.
It looks like there is an environment variable DEBUG=Warn

![image](https://user-images.githubusercontent.com/35405153/233653532-92ba02a4-b7f7-4144-a938-673b923c0704.png)

I can fix the terminal by using a passthrough shell bin kubectl that uset DEBUG but I cannot use the Kubernete Debug

For me it is not happen on WSL but it happens when i connect to a remote linux system using RemoteSSH

**Comment by lorrydriveloper** [comment]
Thanks for your answer; still trying to solve the problem; at the end, I have to open the terminal from my regular terminal, not from the VS code extension, which requires more manual effort as I need to get the pod name & container name, I can't figuring out what is going wrong in my environment.

**Comment by magicsong** [comment]
in my case , uninstall the extenstion mongodb solve the problem

**Comment by lesserror-hxr** [comment]
Thank you, magicsong. I solved this problem with your method. Have you considered giving feedback to the mongodb plugin author?
