### ISSUE TITLE
Unable to open terminal on pod

### ISSUE THREAD

**Issue by pWoLiAn** [vscode-kubernetes-tools/vscode-kubernetes-tools#1187]
![image](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/49567139/d727b2f2-e9d5-4ca2-a2d5-a8dfbea32a7d)

Noticing the issue after the recent latest update. running on windows 11 with remote SSH onto ubuntu 18.04 vm
Terminal closing with error: 
`Error from server (BadRequest): container postgres is not valid for pod postgres-89b45d47-h4gvh`

**Comment by Reilman79** [comment]
I also just ran into this issue. The problem seems to be that the container name is getting some extra whitespace injected in front of it. If you look at the error pop-up, you'll notice that it says `' postgres'` instead of just `'postgres'` after the container flag.

A short term work around until this gets fixed is to just manually run the CLI command directly in a terminal and remove the extra space.

**Comment by eugenebnd** [comment]
Indeed even container selection in UI shows extra indentation 
<img width="524" alt="image" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/25151433/394feb6b-a7ef-441c-90c3-078932657f08">

Reverting the plugin to v1.3.11 fixes the issue.

**Comment by pWoLiAn** [comment]
@Reilman79 Yep. There seems to be some issue in how the container parameter is getting determined. Looks like a regression caused due to the new container feature added in the latest release. Would really appreciate it if you guys could put out a hotfix!!
