### ISSUE TITLE
Launch commands in Windows Bash WSL

### ISSUE THREAD

**Issue by jseguillon** [vscode-kubernetes-tools/vscode-kubernetes-tools#335]
Hello,
Under Win10, I prefer using helm in bash subsystem than in powershell, simply because most of helm plugins are not working on powershell. I'd like to use my helm and kubectl from bash inside VS Code. 

Overidding `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe"` does not apply. I also tried to change `"vs-kubernetes.helm-path": "C:\\WINDOWS\\System32\\bash.exe -c helm""` but then plugin answers : "C:\WINDOWS\System32\bash.exe -c helm does not exist!" 

Is there any way to launch helm and kubectl in bash ?

**Comment by itowlson** [comment]
@radu-matei Sound like you started looking at this - is it okay to assign it to you?

**Comment by radu-matei** [comment]
Surely, you can assign it to me.

@jseguillon - I also tried to add variations of `bash.exe -c` as the path for tools, but that is not going to work for various reasons:

- first, we check if it's Windows, and if so, `.exe` is added - https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/binutil.ts#L45

- then, the command itself (`get pods -o json`, for example) is added on top of the path + binary. Because of how we should call `bash.exe` binaries (mainly `bash.exe -c "kubectl get pods -o json"` - note the quotes), even if we skip adding the `.exe` extension, we still miss the correct quotes.

The fix I have in mind - and @itowlson, @bnookala and @jseguillon - tell me if it's acceptable - would be to add a top level `useWSL` config to the settings, and if true, handle all paths accordingly.

On top of that, there is also the discussion of: which Kubernetes config should we use - the one in Windows (`C:/Users/<user>/.kube/config` - this can be accessed from WSL as `/mnt/c/...`) or the one in WSL (`~/.kube/config`)

Thoughts?

**Comment by itowlson** [comment]
Agree that whether to use the Windows or Linux binaries should be controlled by a setting, rather than kludged in by using a `bash` command line in a tool path.  Note that we don't yet have a consistent way of invoking tools so this might end up touching quite a few places (or you might have to try to rationalise the tool invocation code!).

Re kubeconfig, I would expect that if I used the Linux tools I would want the Linux kubeconfig (unless there was a KUBECONFIG variable pointing to a different one).  This could be a bit tricky for Add Existing Cluster and Create Cluster which would likely end up doing the Wrong Thing unless we also invoked the Azure CLI under bash.

We also need to think about terminal behaviour - that is, if the user wants to use the Linux tools, then presumably when we run commands in terminals, those should be bash terminals rather than PS terminals.

It would possibly also affect the 'Install dependencies' behaviour though I reckon it would be okay just to not offer that option in the presence of the 'use the Linux tools' option - if you are determined enough to ask for the Linux tools then you will surely already have them configured as you like them!

I would also expect some impact on the way we construct paths - I think we call `path.join` directly in quite a few places, and this will presumably use the OS directory separator, and if we pass paths containing Windows directory separators to the Linux version of the tools then we will likely experience suffering.

So this could end up touching a lot of niggly little places and it might take a few iterations to hammer out subtle bugs/quirks... we'd also need to design it in such a way that the first person to update any invocation/pathing code didn't break it (e.g. banning `path.join` and providing a safe wrapper around it)… it doesn't feel like it's "just" a matter of being able to stick a `bash` on the front of the command line!

**Comment by itowlson** [comment]
That won't work with the EXE file extension.  The OS expects EXE files to be PE binaries; you'd need to compile a small binary to at least field the initial invocation.  We could, if it would help, change our check to ignore _any_ existing file extension (and only append `.exe` if the setting had no extension) - then you could name a file `helm-bash.ps1` and be in with a better chance.  I'm still not promising it would work mind!

Do feel free to fork the extension and try removing/changing the `.exe` check yourself if that would help you try this out more quickly.  You'd need to modify `binutil.ts` line 44.  Otherwise we can modify the check and you can try it in the next release.
