### ISSUE TITLE
Only preview releases contain `vsix` files (regular releases do not)

### ISSUE THREAD

**Issue by ibuziuk** [vscode-kubernetes-tools/vscode-kubernetes-tools#527]
Currently, only preview releases contain the `vsix` files and regular releases have only sources i place. Will it be possible to add the `vsix` files also for the regular releases to make it consistent? 

[1] https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by itowlson** [comment]
Regular release VSIXes can be downloaded from the VS Code Marketplace using the Download Extension link on the right.  But from the linked issue it looks like you want to do something more than this?

Anyway, yes... we should aim to provide the VSIXes via the GitHub releases page, but at the moment that's a manual step which is why it hasn't been happening for the Marketplace releases.  We should implement this as part of #262.  What's your urgency on this @ibuziuk?

**Comment by itowlson** [comment]
Assigning this to lucky ol' @bnookala as he assigned himself #262 *grin*.

**Comment by ibuziuk** [comment]
thank you @itowlson
there is no urgency per se, but I would be really gladful if `vsix` for `0.1.17` is manually added since this is the version we are currently using in Eclipse Che and marketplace is pretty vscode centric atm and we are hitting the marketplace rate limit errors every now and than

**Comment by itowlson** [comment]
Sure!  Can you give https://github.com/Azure/vscode-kubernetes-tools/releases/tag/0.1.17 a try please, and let me know if you run into any problems?  I had to do some URL munging which I never trust myself with, but I think it's right...!

**Comment by ibuziuk** [comment]
works like a charm ;-) Thanks again!

**Comment by squillace** [comment]
hmmmm. rate limiting is a bummer.

**Comment by Tatsinnit** [comment]
Thank you so much for this, this issue seems like is resolved and all the current release contains `six` artefacts as part of the release along with the marketplace published with latest as well. 

Artefacts can be checked here: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/releases 

Thank you so much, cc: @squillace , @lstocchi and @itowlson - fyi and in case I missed anything. Closing this issue for now.
