### ISSUE TITLE
Support relative path in tool location settings

### ISSUE THREAD

**Issue by sidewinder12s** [vscode-kubernetes-tools/vscode-kubernetes-tools#940]
Using the following to point VS Code at the Helm install doesn't appear to work:

```json
        "vs-kubernetes": {
            "vs-kubernetes.helm-path.linux": "${workspaceFolder}/tools/bin/helm"
        }
```

Is this expected? I've noticed some extensions support this while others do not.

**Comment by itowlson** [comment]
Hmm, I don't know if VS Code is meant to expand that automatically or if it is extension-specific functionality.  Could you let us know one that does support it and we'll ~see how they do it and copy that~ investigate?  Thanks!

By the way, we recently removed support for configuring binaries at the workspace level, because of the security risk of a malicious workspace [say, a public repo pretending to be useful samples] pointing at a nefarious binary.  So that could be a factor too - are you writing this within a workspace's `settings.json` or at the global level?

**Comment by sidewinder12s** [comment]
The Terraform extension appears to support it, at the workspace level.

I'll have to try without workspace, I was trying to configure it as part of the workspace (for a company wide workspace).

**Comment by kaiba42** [comment]
bump. This is a blocker to creating developer environments with tools and dependencies that are local to a workspace. For example, https://devenv.sh
